import { types } from 'mobx-state-tree';
import { CategoryModel } from '../category/CategoryModel';
import { TagModel } from '../tag/TagModel';

/**
 * Generated PetModelProps
 *
 * Do not edit this file directly, it is generated by openapi-generator.
 */
export const PetModelProps = {
  // ^ Model Properties generated by openapi-generator
  /**
   * @description  Unique identifier for the pet
   * @type integer
   * @format int64
   * @example 10
   * @required
   */
  id: types.maybeNull(types.identifierNumber),
  /**
   * @description  Name of the pet
   * @type string
   * @example doggie
   * @required
   */
  name: types.string,
  /**
   * @type object
   * @nullable
   */
  category: types.optional(types.maybeNull(CategoryModel), {}),
  /**
   * @type array
   * @required
   */
  photoUrls: types.array(types.string),
  /**
   * @type array
   * @nullable
   */
  tags: types.optional(types.maybeNull(types.array(TagModel)), []),
  /**
   * @description  pet status in the store
   * @type string
   * @enum 'available' | 'pending' | 'sold'
   * @nullable
   */
  status: types.optional(
    types.maybeNull(
      types.enumeration('STATUS', ['available', 'pending', 'sold']),
    ),
    'available',
  ),
  // $ Model Properties generated by openapi-generator
};
