import { ApiBase } from '../ApiBase';
import { IOrderModel } from '@/models/order/OrderModel';

/**
 * StoreApiCore
 *
 * Do not edit this file directly, it is generated by openapi-generator.
 */
export class StoreApiCore extends ApiBase {
  // ^ Apis generated by openapi-generator

  /**
   * ## Find purchase order by ID
   * For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
   *
   * @param {number} orderId **(REQUIRED)** {int64} ID of order that needs to be fetched
   * @returns
   */
  public async getOrderById(orderId: number) {
    return this.find<IOrderModel>(`/store/order/${orderId}`);
  }

  /**
   * ## Delete purchase order by ID
   * For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors
   *
   * @param {number} orderId **(REQUIRED)** {int64} ID of the order that needs to be deleted
   * @returns
   */
  public async deleteOrder(orderId: number) {
    return this.delete(`/store/order/${orderId}`);
  }

  /**
   * ## Place an order for a pet
   * Place a new order in the store
   *
   * @param {IOrderModel} payload
   * @returns
   */
  public async placeOrder(payload: IOrderModel) {
    return this.create<IOrderModel>(`/store/order`, payload);
  }

  /**
   * ## Returns pet inventories by status
   * Returns a map of status codes to quantities
   *
   *
   * @returns
   */
  public async getInventory() {
    return this.find(`/store/inventory`);
  }
  // $ Apis generated by openapi-generator
}
