import { types } from 'mobx-state-tree';
import { AddressModel } from '../address/AddressModel';

/**
 * Generated CustomerModelProps
 *
 * Do not edit this file directly, it is generated by openapi-generator.
 */
export const CustomerModelProps = {
  // ^ Model Properties generated by openapi-generator
  /**
   * @type integer
   * @format int64
   * @example 100000
   * @required
   */
  id: types.maybeNull(types.identifierNumber),
  /**
   * @type string
   * @example fehguy
   * @nullable
   */
  username: types.optional(types.maybeNull(types.string), ''),
  /**
   * @type array
   * @nullable
   */
  address: types.optional(types.maybeNull(types.array(AddressModel)), []),
  // $ Model Properties generated by openapi-generator
};
