import { types } from 'mobx-state-tree';

/**
 * Generated ApiResponseModelProps
 *
 * Do not edit this file directly, it is generated by openapi-generator.
 */
export const ApiResponseModelProps = {
  // ^ Model Properties generated by openapi-generator
  /**
   * @type integer
   * @format int32
   * @nullable
   */
  code: types.optional(types.maybeNull(types.number), 0),
  /**
   * @type string
   * @nullable
   */
  type: types.optional(types.maybeNull(types.string), ''),
  /**
   * @type string
   * @nullable
   */
  message: types.optional(types.maybeNull(types.string), ''),
  // $ Model Properties generated by openapi-generator
};
