import { types } from 'mobx-state-tree';

/**
 * Generated AddressModelProps
 *
 * Do not edit this file directly, it is generated by openapi-generator.
 */
export const AddressModelProps = {
  // ^ Model Properties generated by openapi-generator
  /**
   * @type string
   * @example 437 Lytton
   * @nullable
   */
  street: types.optional(types.maybeNull(types.string), ''),
  /**
   * @type string
   * @example Palo Alto
   * @nullable
   */
  city: types.optional(types.maybeNull(types.string), ''),
  /**
   * @type string
   * @example CA
   * @nullable
   */
  state: types.optional(types.maybeNull(types.string), ''),
  /**
   * @type string
   * @example 94301
   * @nullable
   */
  zip: types.optional(types.maybeNull(types.string), ''),
  // $ Model Properties generated by openapi-generator
};
