import { types } from 'mobx-state-tree';

/**
 * Generated CategoryModelProps
 *
 * Do not edit this file directly, it is generated by openapi-generator.
 */
export const CategoryModelProps = {
  // ^ Model Properties generated by openapi-generator
  /**
   * @type integer
   * @format int64
   * @example 1
   * @required
   */
  id: types.maybeNull(types.identifierNumber),
  /**
   * @type string
   * @example Dogs
   * @required
   */
  name: types.string,
  // $ Model Properties generated by openapi-generator
};
