import { types } from 'mobx-state-tree';

/**
 * Generated OrderModelProps
 *
 * Do not edit this file directly, it is generated by openapi-generator.
 */
export const OrderModelProps = {
  // ^ Model Properties generated by openapi-generator
  /**
   * @type integer
   * @format int64
   * @example 10
   * @required
   */
  id: types.identifierNumber,
  /**
   * @type integer
   * @format int64
   * @example 198772
   * @required
   */
  petId: types.number,
  /**
   * @type integer
   * @format int32
   * @example 7
   * @required
   */
  quantity: types.number,
  /**
   * @type string
   * @format date-time
   * @nullable
   */
  shipDate: types.maybeNull(types.string),
  /**
   * @description  Order Status
   * @type string
   * @enum 'placed' | 'approved' | 'delivered'
   * @example approved
   * @nullable
   */
  status: types.maybeNull(
    types.enumeration('STATUS', ['placed', 'approved', 'delivered']),
  ),
  /**
   * @type boolean
   * @nullable
   */
  complete: types.maybeNull(types.boolean),
  // $ Model Properties generated by openapi-generator
};
