import {
  flow,
  Instance,
  SnapshotIn,
  SnapshotOut,
  types,
} from 'mobx-state-tree';
import { withSetPropAction } from '../withSetPropAction';
import {
  TSearchResult,
  TFindResult,
  TCreateResult,
  TUpdateResult,
  TPartialUpdateResult,
  TDeleteResult,
} from '../../services/api';
import { userApi } from '../../services/api/user/UserApi';
import { FetchStates, withFetchStates } from '../withFetchStates';
import { withPagination, IPagination } from '../withPagination';
import { IUserModel } from '../user/UserModel';

const UserStoreProps = {
  // Add Store Properties
  // ^ Store Properties generated by openapi-generator
  // $ Store Properties generated by openapi-generator
};

/**
 * Store description here for TypeScript hints.
 */
export const UserStore = types
  .model('UserStore', UserStoreProps)
  .extend(withFetchStates) // Fetch State
  .extend(withPagination) // Pagination Information
  .actions(withSetPropAction) // Set Property Action
  // DATA FORMATTED VIEWS
  .views((self) => {
    // Custom Views

    return {
      // Expose Data Formatted Views
    };
  })
  // CUSTOM ACTIONS
  .actions((self) => {
    // Custom Actions
    return {
      // Expose Custom Actions
    };
  })
  // GENERATED ACTIONS
  .actions((self) => {
    // ^ Actions generated by openapi-generator

    /**
     * ## Get user by user name
     *
     * @tags `user`
     * @param {string} username **REQUIRED**  The name that needs to be fetched. Use user1 for testing.
     */
    const getUserByName = flow(function* (username: string) {
      if (self.isPending) return;
      self.pending();
      const response = yield userApi.getUserByName(username);
      if (response.kind === 'ok') {
        // TODO - TRANSLATE RESPONSE TO STORE
        const data = response.data.data as IUserModel;

        // --------------------------------------------------------------------
        console.log('getUserByName()', JSON.stringify(data, null, 2));
        throw new Error('TODO - TRANSLATE RESPONSE TO STORE getUserByName()');
        // --------------------------------------------------------------------

        self.done();
      } else {
        self.error(response);
        console.error(JSON.stringify(response, null, 2));
      }
    });

    /**
     * ## Update user
     * This can only be done by the logged in user.
     * @tags `user`
     * @param {string} username **REQUIRED**  name that need to be deleted
     * @param {any} payload  {any} Update an existent user in the store
     */
    const updateUser = flow(function* (username: string, payload: any) {
      if (self.isPending) return;
      self.pending();
      const response = yield userApi.updateUser(username, payload);
      if (response.kind === 'ok') {
        // TODO - TRANSLATE RESPONSE TO STORE
        const data = response.data.data as null;

        // --------------------------------------------------------------------
        console.log('updateUser()', JSON.stringify(data, null, 2));
        throw new Error('TODO - TRANSLATE RESPONSE TO STORE updateUser()');
        // --------------------------------------------------------------------

        self.done();
      } else {
        self.error(response);
        console.error(JSON.stringify(response, null, 2));
      }
    });

    /**
     * ## Delete user
     * This can only be done by the logged in user.
     * @tags `user`
     * @param {string} username **REQUIRED**  The name that needs to be deleted
     */
    const deleteUser = flow(function* (username: string) {
      if (self.isPending) return;
      self.pending();
      const response = yield userApi.deleteUser(username);
      if (response.kind === 'ok') {
        // TODO - TRANSLATE RESPONSE TO STORE
        const data = response.data.data as null;

        // --------------------------------------------------------------------
        console.log('deleteUser()', JSON.stringify(data, null, 2));
        throw new Error('TODO - TRANSLATE RESPONSE TO STORE deleteUser()');
        // --------------------------------------------------------------------

        self.done();
      } else {
        self.error(response);
        console.error(JSON.stringify(response, null, 2));
      }
    });

    /**
     * ## Logs out current logged in user session
     *
     * @tags `user`
     *
     */
    const logoutUser = flow(function* () {
      if (self.isPending) return;
      self.pending();
      const response = yield userApi.logoutUser();
      if (response.kind === 'ok') {
        // TODO - TRANSLATE RESPONSE TO STORE
        const data = response.data.data as null;

        // --------------------------------------------------------------------
        console.log('logoutUser()', JSON.stringify(data, null, 2));
        throw new Error('TODO - TRANSLATE RESPONSE TO STORE logoutUser()');
        // --------------------------------------------------------------------

        self.done();
      } else {
        self.error(response);
        console.error(JSON.stringify(response, null, 2));
      }
    });

    /**
     * ## Logs user into the system
     *
     * @tags `user`
     * @param {string} username   The user name for login
     * @param {string} password   The password for login in clear text
     */
    const loginUser = flow(function* (username: string, password: string) {
      if (self.isPending) return;
      self.pending();
      const response = yield userApi.loginUser(username, password);
      if (response.kind === 'ok') {
        // TODO - TRANSLATE RESPONSE TO STORE
        const data = response.data.data as null;

        // --------------------------------------------------------------------
        console.log('loginUser()', JSON.stringify(data, null, 2));
        throw new Error('TODO - TRANSLATE RESPONSE TO STORE loginUser()');
        // --------------------------------------------------------------------

        self.done();
      } else {
        self.error(response);
        console.error(JSON.stringify(response, null, 2));
      }
    });

    /**
     * ## Creates list of users with given input array
     * Creates list of users with given input array
     * @tags `user`
     * @param {any} payload  {any}
     */
    const createUsersWithListInput = flow(function* (payload: any) {
      if (self.isPending) return;
      self.pending();
      const response = yield userApi.createUsersWithListInput(payload);
      if (response.kind === 'ok') {
        // TODO - TRANSLATE RESPONSE TO STORE
        const data = response.data.data as IUserModel;

        // --------------------------------------------------------------------
        console.log(
          'createUsersWithListInput()',
          JSON.stringify(data, null, 2),
        );
        throw new Error(
          'TODO - TRANSLATE RESPONSE TO STORE createUsersWithListInput()',
        );
        // --------------------------------------------------------------------

        self.done();
      } else {
        self.error(response);
        console.error(JSON.stringify(response, null, 2));
      }
    });

    /**
     * ## Create user
     * This can only be done by the logged in user.
     * @tags `user`
     * @param {any} payload  {any} Created user object
     */
    const createUser = flow(function* (payload: any) {
      if (self.isPending) return;
      self.pending();
      const response = yield userApi.createUser(payload);
      if (response.kind === 'ok') {
        // TODO - TRANSLATE RESPONSE TO STORE
        const data = response.data.data as IUserModel;

        // --------------------------------------------------------------------
        console.log('createUser()', JSON.stringify(data, null, 2));
        throw new Error('TODO - TRANSLATE RESPONSE TO STORE createUser()');
        // --------------------------------------------------------------------

        self.done();
      } else {
        self.error(response);
        console.error(JSON.stringify(response, null, 2));
      }
    });
    // $ Actions generated by openapi-generator
    return {
      // ^ Expose actions generated by openapi-generator
      getUserByName,
      updateUser,
      deleteUser,
      logoutUser,
      loginUser,
      createUsersWithListInput,
      createUser,
      // $ Expose actions generated by openapi-generator
    };
  });

export interface IUserStore extends Instance<typeof UserStore> {}
export interface IUserSnapshotOut extends SnapshotOut<typeof UserStore> {}
export interface IUserStoreSnapshotIn extends SnapshotIn<typeof UserStore> {}
export type TUserStorePropKeys = keyof IUserStoreSnapshotIn & string;
