import { types } from 'mobx-state-tree';

/**
 * Generated UserModelProps
 *
 * Do not edit this file directly, it is generated by openapi-generator.
 */
export const UserModelProps = {
  // ^ Model Properties generated by openapi-generator
  /**
   * @type integer
   * @format int64
   * @example 10
   * @required
   */
  id: types.maybeNull(types.identifierNumber),
  /**
   * @type string
   * @example theUser
   * @required
   */
  username: types.string,
  /**
   * @type string
   * @example John
   * @nullable
   */
  firstName: types.optional(types.maybeNull(types.string), ''),
  /**
   * @type string
   * @example James
   * @nullable
   */
  lastName: types.optional(types.maybeNull(types.string), ''),
  /**
   * @type string
   * @example john@email.com
   * @nullable
   */
  email: types.optional(types.maybeNull(types.string), ''),
  /**
   * @type string
   * @example 12345
   * @nullable
   */
  password: types.optional(types.maybeNull(types.string), ''),
  /**
   * @type string
   * @example 12345
   * @nullable
   */
  phone: types.optional(types.maybeNull(types.string), ''),
  /**
   * @description  User Status
   * @type integer
   * @format int32
   * @example 1
   * @required
   */
  userStatus: types.number,
  // $ Model Properties generated by openapi-generator
};
